#!/bin/bash
#
# Determine a version string to be used in file names etc.
# The script will use tags, the git hash, or "unknown".
#    "v5.0.1" // tag name
#    "v5.0.0-218-g1644446e64" // tag + delta + hash
#    "g1644446e64" // hash only
#
# If -j is specified, it will also append -j + BUILD_NUMBER.
#    "g1644446e64-j145"
#
# Arguments:
#   -j: use Jenkins variables
#   -d: set CWD as the same directory as this script
#   --dirty: use dirty option in git describe

use_jenkins=false

while [ $# -gt 0 ]; do
    case "$1" in
    -j)
        use_jenkins=true
        shift
        ;;
    -d)
        cd "$(dirname "$0")" || exit 1
        shift
        ;;
    --dirty)
        describe_opts+=" --dirty"
        shift
        ;;
    *)
        echo "Unknown argument: $1"
        exit 1
        ;;
    esac
done

git_describe=$(git describe --tags --always $describe_opts 2>/dev/null)
git_hash=$(git rev-parse HEAD 2>/dev/null)

# Jenkins sets $BUILD_NUMBER
if [ "$BUILD_NUMBER" ] && $use_jenkins; then
    # "v5.0.1-j145"
    #   or "v5.0.0-218-g1644446e64-j145"
    #   or "g1644446e64-j145"
    echo "${git_describe:-g${git_hash:0:8}}-j${BUILD_NUMBER}"
    exit 0
fi

# "v5.0.0-218-g1644446e64"
if [ "$git_hash" ]; then
    echo "${git_describe:-g${git_hash:0:8}}"
    exit 0
fi

echo "unknown"
